### ISSUE TITLE
Readme-förbättringar

### ISSUE THREAD

**Issue by JensRantil** [kirei/tls-report#10]
Finns det unit-tester? Hur kör jag denna tjänst lokalt om jag vill utveckla? Hur bygger jag projektet? Möjligtvis också nämna licens.

**Comment by JensRantil** [comment]
Föreslår också att en `LICENSE` full skapas i roten.

**Comment by jschlyter** [comment]
För att köra en testomgång gör man "make scan", några tester finns inte än.

**Comment by JensRantil** [comment]
Fortfarande inte dokumenterat i readme så jag anser inte att denna issue kan stängas än.

**Comment by jschlyter** [comment]
TODO: Dokumentera hur man kör testerna i README

**Comment by jschlyter** [comment]
ok så Jens?

**Comment by JensRantil** [comment]
:+1:
