### ISSUE TITLE
Bug or just a temporary error at data collection?

### ISSUE THREAD

**Issue by fsoderblom** [kirei/tls-report#16]
<img width="1482" alt="tls-rapporten" src="https://cloud.githubusercontent.com/assets/3097851/10676547/5ba212e2-7907-11e5-9068-cff3799a4f90.png">

**Comment by jschlyter** [comment]
Likely a data collection error, I'll re-run the dataset shortly.

**Comment by jschlyter** [comment]
This was actually a IPv6 reachable issue. I've now flagged domain with unreachable IPv6 (e.g. sunet.se).
