### ISSUE TITLE
När var senaste uppdateringen

### ISSUE THREAD

**Issue by johnsonbrothers** [kirei/tls-report#19]
I informationen om er underbara (jag tycker det. Jättebra!) tjänst, https://www.kirei.se/2015/06/23/tls/ står att den uppdateras periodiskt.
Jag önskar att tidpunkt för senaste uppdateringstillfället presenterar någonstans på sidan.
Alternativt att det periodiska beskrivs, exempelvis med längden på perioden :-)

**Comment by jschlyter** [comment]
Perioden är fn oregelbunden eftersom det inte körs automatiskt, men senaste datum står längst ner på sidan. Hoppas det blir mer tid framöver att göra detta mer automatiserat.

**Comment by johnsonbrothers** [comment]
Oj, där syns ett datum ja. Tack.
