### ISSUE TITLE
Länsförsäkringar AB 

### ISSUE THREAD

**Issue by wearefaces** [kirei/tls-report#21]
Ni presenterar ju fel information. LFAB använder SSL certificate fast det stå att det finns inga certifikater på LFAB

**Comment by jschlyter** [comment]
lansforsakringar.se presenterar ett certifikat för www1.lansforsakringar.se, det verkar inte rimligt. www.lansforsakringar.se har ett annat cert (ett SHA-1 cert som går ut den 1 juni).
