### ISSUE TITLE
Lite fler domäner

### ISSUE THREAD

**Issue by secworks** [kirei/tls-report#4]
edvina.se
secode.se
cert.se
sesec.se
dfri.se
addpro.se
cybercom.se
afconsult.com
sectra.com
bitsec.se
netresec.com
halon.se

**Comment by secworks** [comment]
nohau.se
ericsson.com

Och de största börsbolagen:
https://sv.wikipedia.org/wiki/Lista_%C3%B6ver_Sveriges_st%C3%B6rsta_f%C3%B6retag

**Comment by fsoderblom** [comment]
xpd.se - https://www.ssllabs.com/ssltest/analyze.html?d=xpd.se

**Comment by secworks** [comment]
Precis, ni gör rätt och bra. Till skillnad från en del andra.

**Comment by jschlyter** [comment]
Please send pull requests.
